name: bank-card-dev
services:
  db:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  app:
    image: bank-rest:0.0.1
    container_name: bank-rest
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres_db'
    ports:
      - '8080:8080'
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
  pgadmin_data:

